version: '3'
services:
    schedule:
        image: esmsecbuzzer/nmapandflowscan:1.0.0
        network_mode : "host"
        # command: "bash -c 'while :; do sleep 60; done'"
        environment:
            - ES_IP=localhost
            - ES_PORT=19200
            - ORG1CODE=01
            - ORG2CODE=02
            - ORG3CODE=03
        #FLOW SCAN PARAMETER
            - FLOWSCAN_SCHED_PERIOD=1
            - INTERFACE=$IF_NAME
            - FLOWSCAN_SOURCEIP=192.168.70.0/24
            - FLOWSCAN_DESTIP=192.168.70.0/24
            - PACKETCOUNT=1000
            - TOTALCOUNT=100
        #NMAP SCAN PARAMETER 
            - NMAPSCAN_SCHED_PERIOD=1
            - NMAPSCAN_IP=192.168.70.0/24
