version: '2.1'
services:
    fluentd:
        image: csti/fluentd:v4
        build:
            context: "./fluentd_image/"
            dockerfile: "Dockerfile"
        depends_on:
            - cron
        ports:
            - 24224:24224
            - 514:514/udp
            - 515:515/udp
        volumes:
            - "$FLUENTD_BUFFER_PATH:/fluentd/Buffers"
            - "./conf/suricata.conf:/fluentd/etc/fluent.conf"
            - "/usr/share/zoneinfo/ROC:/etc/localtime:ro" 
            - "$SURICATA_LOG_PATH:/fluentd/suricata/"
        network_mode: host
        restart: always
